version: "3.8"

services:
  address-address_sanitization_service:
    build: .
    container_name: "address_sanitization_service"

    ports:
      - "8000:80"
    # (You can also use .env or secrets if you prefer.)
    environment:
      - AZURE_MAPS_KEY=${AZURE_MAPS_KEY:-YOUR_AZURE_MAPS_KEY}
