configs:
  rbac:
    policy.default: 'role:readonly'
  cm:
    users.anonymous.enabled: "true"
    timeout.reconciliation: 10s
  params:
    server.insecure: true
    application.namespaces: "*"
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: argocd.joaquin.dev
    hosts: 
    - argocd.joaquin.dev
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.joaquin.dev
    https: true
